apiVersion: autoscaling/v2beta2 # TODO autoscaling/v2 
kind: HorizontalPodAutoscaler
metadata:
  name: samplewebapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: samplewebapp
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
