apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-app
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: my-app
            image: IMAGE_NAME
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
